# Generated by Django 5.2.5 on 2025-08-27 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingperson', '0003_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(choices=[('webcam', 'Webcam'), ('ip', 'IP Camera'), ('rtsp', 'RTSP Stream')], default='webcam', max_length=10),
        ),
        migrations.AddField(
            model_name='camera',
            name='webcam_index',
            field=models.IntegerField(default=0, help_text='Index for webcam (usually 0 for default)'),
        ),
        migrations.AddField(
            model_name='location',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='missingperson.camera'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='port',
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
    ]
