# Generated by Django 5.2.5 on 2025-08-29 03:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingperson', '0004_camera_camera_type_camera_webcam_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='password',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='port',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='rtsp_url',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='username',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='webcam_index',
        ),
        migrations.RemoveField(
            model_name='location',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='face_encoding',
        ),
        migrations.AddField(
            model_name='camera',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='camera',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='source',
            field=models.CharField(default='manual', help_text='Camera index (0, 1, etc.) for webcam, IP address for IP camera, or RTSP URL', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(choices=[('webcam', 'Webcam'), ('ip', 'IP Camera'), ('rtsp', 'RTSP Stream')], max_length=10),
        ),
    ]
