# Generated by Django 5.2.5 on 2025-09-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingperson', '0005_remove_camera_ip_address_remove_camera_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='camera',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
